name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gen_artifacts:
    runs-on: ubuntu-20.04
    container: ghcr.io/domi3006/docker-kicad-ci:latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: run artifacts
      run: |
        make all
    - name: Retrieve results
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          Fabrication/
