name: create-release

on:
  push:
    tags:
      - '*'

jobs:
  gen_artifacts:
    runs-on: ubuntu-20.04
    container: ghcr.io/domi3006/docker-kicad-ci:latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: create artifacts
      run: |
        make all
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          Fabrication/

  create_release:
    runs-on: ubuntu-20.04
    needs: gen_artifacts
    steps:
    - name: get artifacts
      uses: actions/download-artifact@v2
      id: get_artifacts
      with:
        name: artifacts
        path: Fabrication/
    - name: create release-zip from artifacts
      run: |
        cd ${{steps.get_artifacts.outputs.download-path}}; zip -r ../fabrication *
    - name: upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./fabrication.zip
        asset_name: fabrication
        tag: ${{ github.ref }}
        overwrite: true
        body: Release ${{ github.ref }}
